const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const zonesUI=document.getElementById('zonesUI');
const lastResult=document.getElementById('lastResult');
const soundBtn=document.getElementById('soundBtn');
const launchBtn=document.getElementById('launchBtn');
const togglePanelBtn=document.getElementById('togglePanelBtn');
const panel=document.getElementById('panel');
let soundOn=true,running=false,pig=null,sparkles=[];
const defaults=[{name:'Tiny Oink',amount:'x1',sub:['5','10','15']},{name:'Big Oink',amount:'x2',sub:['25','50','75']},{name:'Mega Oink',amount:'x5',sub:['100','250','500']}];
const zones=JSON.parse(localStorage.getItem('oinkZones')||'null')||defaults;
function saveZones(){localStorage.setItem('oinkZones',JSON.stringify(zones));}
function dpr(){return devicePixelRatio||1}
function resize(){canvas.width=canvas.clientWidth*dpr();canvas.height=canvas.clientHeight*dpr();}
window.addEventListener('resize',resize);resize();
function playTone(freq,dur,shape='triangle',gain=0.06){if(!soundOn)return;const AC=window.AudioContext||window.webkitAudioContext;playTone.ac=playTone.ac||new AC();const ac=playTone.ac,o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);o.type=shape;const n=ac.currentTime;o.frequency.setValueAtTime(freq,n);o.frequency.exponentialRampToValueAtTime(freq*1.35,n+dur);g.gain.setValueAtTime(gain,n);g.gain.exponentialRampToValueAtTime(.0001,n+dur+.03);o.start(n);o.stop(n+dur+.05);}
function oink(){playTone(330,.08,'square',.04);playTone(220,.11,'sawtooth',.03);}
function buildUI(){zonesUI.innerHTML='';zones.forEach((z,i)=>{const box=document.createElement('div');box.className='zonebox';box.innerHTML=`<div class="zonehead"><strong>Zone ${i+1}</strong><span class="gear">⚙️</span></div><div class="zonerows"><input data-k="name" value="${z.name}"><input data-k="amount" value="${z.amount}"><button class="btn mini" data-save>Save</button></div><div class="zonerows" style="margin-top:8px"><input data-sub="0" value="${z.sub[0]||''}"><input data-sub="1" value="${z.sub[1]||''}"><input data-sub="2" value="${z.sub[2]||''}"></div>`;const subs=box.querySelectorAll('[data-sub]');subs.forEach(el=>el.style.display='none');box.querySelector('.gear').onclick=()=>subs.forEach(el=>el.style.display=el.style.display==='none'?'block':'none');box.querySelector('[data-save]').onclick=()=>{box.querySelectorAll('input').forEach(inp=>{if(inp.dataset.k)z[inp.dataset.k]=inp.value;if(inp.dataset.sub!==undefined)z.sub[+inp.dataset.sub]=inp.value;});saveZones();buildUI();};zonesUI.appendChild(box);});}
function zoneForX(x){const w=canvas.width;return Math.max(0,Math.min(zones.length-1,Math.floor(x/(w/zones.length))));}
function launch(){if(running)return;if(playTone.ac&&playTone.ac.state==='suspended')playTone.ac.resume();running=true;oink();playTone(210,.06,'triangle',.05);lastResult.textContent='Launched!';const h=canvas.height;pig={x:92*dpr(),y:h-92*dpr(),vx:8*dpr(),vy:-13*dpr(),r:18*dpr(),spin:0,trail:[]};}
function update(){const w=canvas.width,h=canvas.height,ground=h-40*dpr();sparkles=sparkles.filter(s=>s.life>0);sparkles.forEach(s=>{s.x+=s.vx;s.y+=s.vy;s.vy+=.18*dpr();s.life--;});if(pig){pig.vy+=.45*dpr();pig.x+=pig.vx;pig.y+=pig.vy;pig.spin+=pig.vx*.08;pig.trail.push({x:pig.x,y:pig.y,life:18});pig.trail=pig.trail.slice(-18);if(pig.x-pig.r<0||pig.x+pig.r>w){pig.vx*=-.88;pig.x=Math.max(pig.r,Math.min(w-pig.r,pig.x));oink();}if(pig.y+pig.r>ground){pig.y=ground-pig.r;pig.vy*=-.7;pig.vx*=.93;oink();if(Math.abs(pig.vy)<1.2*dpr()&&Math.abs(pig.vx)<.7*dpr()){const z=zones[zoneForX(pig.x)];lastResult.textContent=`${z.name} ${z.amount} (${z.sub.join(' / ')})`;playTone(470,.11,'triangle',.05);for(let i=0;i<18;i++)sparkles.push({x:pig.x,y:pig.y,vx:(Math.random()-.5)*5*dpr(),vy:(Math.random()-.8)*5*dpr(),life:30+Math.random()*20});pig=null;running=false;}}}}
function draw(){const w=canvas.width,h=canvas.height,ground=h-40*dpr(),zW=w/zones.length;ctx.clearRect(0,0,w,h);const bg=ctx.createLinearGradient(0,0,w,h);bg.addColorStop(0,'rgba(255,102,184,.10)');bg.addColorStop(1,'rgba(90,208,255,.10)');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);const grass=ctx.createLinearGradient(0,ground,w,h);grass.addColorStop(0,'#59d56e');grass.addColorStop(.55,'#3aa955');grass.addColorStop(1,'#1f6b35');ctx.fillStyle=grass;ctx.fillRect(0,ground,w,h-ground);for(let i=0;i<zones.length;i++){ctx.fillStyle=i%2?'rgba(90,208,255,.16)':'rgba(255,102,184,.16)';ctx.fillRect(i*zW,ground,zW,40*dpr());ctx.strokeStyle='rgba(255,255,255,.18)';ctx.strokeRect(i*zW,ground,zW,40*dpr());ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font=`${18*dpr()}px system-ui`;ctx.fillText(zones[i].name,i*zW+zW/2,ground+18*dpr());ctx.font=`${14*dpr()}px system-ui`;ctx.fillStyle='#e8fff0';ctx.fillText(zones[i].amount,i*zW+zW/2,ground+34*dpr());}ctx.fillStyle='rgba(255,255,255,.18)';ctx.fillRect(0,ground-8*dpr(),w,8*dpr());ctx.save();ctx.fillStyle='rgba(255,255,255,.08)';ctx.strokeStyle='rgba(255,255,255,.22)';ctx.lineWidth=2*dpr();ctx.beginPath();ctx.roundRect(28*dpr(),h-155*dpr(),110*dpr(),85*dpr(),18*dpr());ctx.fill();ctx.stroke();ctx.fillStyle='#ffb6d9';ctx.beginPath();ctx.arc(50*dpr(),h-112*dpr(),17*dpr(),0,Math.PI*2);ctx.fill();ctx.fillStyle='#1b1530';ctx.font=`bold ${18*dpr()}px system-ui`;ctx.fillText('🐷',43*dpr(),h-106*dpr());ctx.fillStyle='rgba(255,255,255,.92)';ctx.beginPath();ctx.moveTo(120*dpr(),h-128*dpr());ctx.lineTo(175*dpr(),h-120*dpr());ctx.lineTo(120*dpr(),h-112*dpr());ctx.closePath();ctx.fill();ctx.fillStyle='rgba(90,208,255,.45)';ctx.fillRect(108*dpr(),h-124*dpr(),20*dpr(),8*dpr());ctx.restore();if(pig){pig.trail.forEach(t=>{ctx.globalAlpha=t.life/18*.35;ctx.fillStyle='#ff7cc9';ctx.beginPath();ctx.arc(t.x,t.y,6*dpr()*(t.life/18),0,Math.PI*2);ctx.fill();});ctx.globalAlpha=1;ctx.save();ctx.translate(pig.x,pig.y);ctx.rotate(pig.spin);ctx.fillStyle='#ffb6d9';ctx.beginPath();ctx.arc(0,0,pig.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff78bc';ctx.beginPath();ctx.arc(pig.r*.8,0,pig.r*.45,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-pig.r*.35,-pig.r*.2,3.5*dpr(),0,Math.PI*2);ctx.arc(pig.r*.1,-pig.r*.2,3.5*dpr(),0,Math.PI*2);ctx.fill();ctx.fillStyle='#2a1738';ctx.beginPath();ctx.arc(-pig.r*.35,-pig.r*.2,1.3*dpr(),0,Math.PI*2);ctx.arc(pig.r*.1,-pig.r*.2,1.3*dpr(),0,Math.PI*2);ctx.fill();ctx.restore();}sparkles.forEach(s=>{ctx.globalAlpha=Math.max(0,s.life/50);ctx.fillStyle='#5ad0ff';ctx.fillRect(s.x,s.y,3*dpr(),3*dpr());});ctx.globalAlpha=1;}
function loop(){update();draw();requestAnimationFrame(loop);}loop();
launchBtn.onclick=()=>{if(playTone.ac&&playTone.ac.state==='suspended')playTone.ac.resume();launch();};
soundBtn.onclick=()=>{soundOn=!soundOn;soundBtn.textContent=`Sound: ${soundOn?'On':'Off'}`};
togglePanelBtn.onclick=()=>{panel.classList.toggle('hidden');togglePanelBtn.textContent=panel.classList.contains('hidden')?'Show Customize':'Hide Customize';};
buildUI();